name: Frontend Lint

on:
  push:
    branches:
      - development
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Biome
        run: npm install -g @biomejs/biome
      - name: Run Biome
        run: biome check .
